# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

from django.db import models

class Tbl1Hemato(models.Model):
    #id = models.IntegerField(unique=True)
    folio = models.IntegerField(null=True, blank=True)
    nombre_medico = models.CharField(max_length=450, blank=True)
    codigo_medico = models.CharField(max_length=15, blank=True)
    hospital = models.CharField(max_length=750, blank=True)
    institucion = models.CharField(max_length=150, blank=True)
    estado = models.CharField(max_length=75, blank=True)
    zona = models.CharField(max_length=60, blank=True)
    listado = models.CharField(max_length=6, blank=True)
    fecha_llenado = models.DateField(null=True, blank=True)
    cup = models.CharField(max_length=9, blank=True)
    hospitalizado = models.CharField(max_length=6, blank=True)
    referido = models.CharField(max_length=6, blank=True)
    referido_especialidad = models.CharField(max_length=225, blank=True)
    sexo = models.CharField(max_length=30, blank=True)
    edad = models.IntegerField(null=True, blank=True)
    peso = models.IntegerField(null=True, blank=True)
    talla = models.FloatField(null=True, blank=True)
    superficie_corporal = models.FloatField(null=True, blank=True)
    usuario = models.CharField(max_length=60, blank=True)
    fecha_captura = models.DateField(null=True, blank=True)
    booster = models.CharField(max_length=6, blank=True)
    booster_tipo = models.CharField(max_length=60, blank=True)
    pacientes_en_30_dias = models.IntegerField(null=True, blank=True)
    pacientes_con_lnh = models.IntegerField(null=True, blank=True)
    pacientes_nuevos = models.IntegerField(null=True, blank=True)
    pacientes_agresivos = models.IntegerField(null=True, blank=True)
    pacientes_indolentes = models.IntegerField(null=True, blank=True)
    pacientes_indolentes_induccion = models.IntegerField(null=True, blank=True)
    pacientes_indolentes_mantenimiento = models.IntegerField(null=True, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl1_hemato'

class Tbl10Hemato(models.Model):
    idtbl_10 = models.IntegerField(primary_key=True)
    idtbl_1 = models.ForeignKey(Tbl1Hemato, db_column='idtbl_1')
    i1_respuesta = models.CharField(max_length=150, blank=True)
    i1_eritropoyetina = models.CharField(max_length=765, blank=True)
    i1_eritropoyetina_otro = models.CharField(max_length=765, blank=True)
    i1_ipi = models.CharField(max_length=60, blank=True)
    i1_fipi = models.CharField(max_length=60, blank=True)
    i1_tac = models.IntegerField(null=True, blank=True)
    i1_biopsia = models.IntegerField(null=True, blank=True)
    i1_aspirado_mo = models.IntegerField(null=True, blank=True)
    i1_bh = models.IntegerField(null=True, blank=True)
    i1_ldh = models.IntegerField(null=True, blank=True)
    i1_microglobulina = models.IntegerField(null=True, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl10_hemato'

class Tbl11Hemato(models.Model):
    idtbl_11 = models.IntegerField(primary_key=True)
    idtbl_1 = models.ForeignKey(Tbl1Hemato, db_column='idtbl_1')
    i2_respuesta = models.CharField(max_length=150, blank=True)
    i2_eritropoyetina = models.CharField(max_length=765, blank=True)
    i2_eritropoyetina_otro = models.CharField(max_length=765, blank=True)
    i2_ipi = models.CharField(max_length=60, blank=True)
    i2_fipi = models.CharField(max_length=60, blank=True)
    i2_tac = models.IntegerField(null=True, blank=True)
    i2_biopsia = models.IntegerField(null=True, blank=True)
    i2_aspirado_mo = models.IntegerField(null=True, blank=True)
    i2_bh = models.IntegerField(null=True, blank=True)
    i2_ldh = models.IntegerField(null=True, blank=True)
    i2_microglobulina = models.IntegerField(null=True, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl11_hemato'

class Tbl12Hemato(models.Model):
    idtbl_12 = models.IntegerField(primary_key=True)
    idtbl_1 = models.ForeignKey(Tbl1Hemato, db_column='idtbl_1')
    i3_respuesta = models.CharField(max_length=150, blank=True)
    i3_eritropoyetina = models.CharField(max_length=765, blank=True)
    i3_eritropoyetina_otro = models.CharField(max_length=765, blank=True)
    i3_ipi = models.CharField(max_length=60, blank=True)
    i3_fipi = models.CharField(max_length=60, blank=True)
    i3_tac = models.IntegerField(null=True, blank=True)
    i3_biopsia = models.IntegerField(null=True, blank=True)
    i3_aspirado_mo = models.IntegerField(null=True, blank=True)
    i3_bh = models.IntegerField(null=True, blank=True)
    i3_ldh = models.IntegerField(null=True, blank=True)
    i3_microglobulina = models.IntegerField(null=True, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl12_hemato'

class Tbl13Hemato(models.Model):
    idtbl_13 = models.IntegerField(primary_key=True)
    idtbl_1 = models.ForeignKey(Tbl1Hemato, db_column='idtbl_1')
    candidato_2da_linea = models.CharField(max_length=150, db_column='candidato 2da linea', blank=True) # Field renamed to remove spaces. Field name made lowercase.
    candidato_mantenimiento = models.CharField(max_length=150, db_column='candidato mantenimiento', blank=True) # Field renamed to remove spaces. Field name made lowercase.
    i4_ipi = models.CharField(max_length=60, blank=True)
    i4_fipi = models.CharField(max_length=60, blank=True)
    i4_tac = models.IntegerField(null=True, blank=True)
    i4_biopsia = models.IntegerField(null=True, blank=True)
    i4_aspirado_mo = models.IntegerField(null=True, blank=True)
    i4_bh = models.IntegerField(null=True, blank=True)
    i4_ldh = models.IntegerField(null=True, blank=True)
    i4_microglobulina = models.IntegerField(null=True, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl13_hemato'

class Tbl2Hemato(models.Model):
    id_tbl2 = models.IntegerField(primary_key=True)
    id_tbl1 = models.ForeignKey(Tbl1Hemato, db_column='id_tbl1')
    tipo_linfoma = models.CharField(max_length=300)
    tipo_linfoma_otros = models.CharField(max_length=150, blank=True)
    linaje_celular = models.CharField(max_length=15, blank=True)
    clasificacion_oms = models.CharField(max_length=300, blank=True)
    ipi_indice = models.IntegerField(null=True, blank=True)
    ipi_riesgo = models.CharField(max_length=45, blank=True)
    flipi_indice = models.IntegerField(null=True, blank=True)
    flipi_riesgo = models.CharField(max_length=45, blank=True)
    estadio_actual = models.CharField(max_length=15, blank=True)
    etapa_actual = models.CharField(max_length=9, blank=True)
    estadio_diagnostico = models.CharField(max_length=9, blank=True)
    etapa_diagnostico = models.CharField(max_length=15, blank=True)
    fecha_diagnostico = models.DateField(null=True, blank=True)
    ver_esperar = models.CharField(max_length=6, blank=True)
    ver_esperar_m = models.IntegerField(null=True, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl2_hemato'

class Tbl3Hemato(models.Model):
    id_tbl3 = models.IntegerField(primary_key=True)
    id_tbl1 = models.ForeignKey(Tbl1Hemato, db_column='id_tbl1')
    pih_cd3 = models.CharField(max_length=6, blank=True)
    pih_cd3_res = models.CharField(max_length=6, blank=True)
    pih_cd5 = models.CharField(max_length=6, blank=True)
    pih_cd5_res = models.CharField(max_length=6, blank=True)
    pih_cd10 = models.CharField(max_length=6, blank=True)
    pih_cd10_res = models.CharField(max_length=6, blank=True)
    pih_cd20 = models.CharField(max_length=6, blank=True)
    pih_cd20_res = models.CharField(max_length=6, blank=True)
    pih_cd30 = models.CharField(max_length=6, blank=True)
    pih_cd30_res = models.CharField(max_length=6, blank=True)
    pih_cd45 = models.CharField(max_length=6, blank=True)
    pih_cd45_res = models.CharField(max_length=6, blank=True)
    pih_cd56 = models.CharField(max_length=6, blank=True)
    pih_cd56_res = models.CharField(max_length=6, blank=True)
    pih_bcl6 = models.CharField(max_length=6, blank=True)
    pih_bcl6_res = models.CharField(max_length=6, blank=True)
    pih_bcl2 = models.CharField(max_length=6, blank=True)
    pih_bcl2_res = models.CharField(max_length=6, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl3_hemato'

class Tbl4Hemato(models.Model):
    id_tbl4 = models.IntegerField(primary_key=True)
    id_tbl1 = models.ForeignKey(Tbl1Hemato, db_column='id_tbl1')
    actual_tratamiento_linea = models.CharField(max_length=30, blank=True)
    actual_tratamiento_tipo = models.CharField(max_length=45, blank=True)
    actual_mabthera = models.CharField(max_length=30, blank=True)
    actual_despues_de_cuantos_meses_recayo = models.IntegerField(null=True, blank=True)
    primer_esquema_upl = models.CharField(max_length=6, blank=True)
    monoterapia_am = models.CharField(max_length=6, blank=True)
    actual_utilizo_fec = models.CharField(max_length=6, blank=True)
    actual_desarrollo_neutropenia = models.CharField(max_length=6, blank=True)
    actual_ciclos_mantenimiento = models.IntegerField(null=True, blank=True)
    actual_marca_1 = models.CharField(max_length=150, blank=True)
    actual_sal_1 = models.CharField(max_length=150, blank=True)
    actual_dosis_1 = models.IntegerField(null=True, blank=True)
    actual_ciclos_planeados_1 = models.IntegerField(null=True, blank=True)
    actual_ciclos_aplicados_1 = models.IntegerField(null=True, blank=True)
    actual_intervalo_1 = models.IntegerField(null=True, blank=True)
    actual_marca_2 = models.CharField(max_length=150, blank=True)
    actual_sal_2 = models.CharField(max_length=150, blank=True)
    actual_dosis_2 = models.IntegerField(null=True, blank=True)
    actual_ciclos_planeados_2 = models.IntegerField(null=True, blank=True)
    actual_ciclos_aplicados_2 = models.IntegerField(null=True, blank=True)
    actual_intervalo_2 = models.IntegerField(null=True, blank=True)
    actual_marca_3 = models.CharField(max_length=150, blank=True)
    actual_sal_3 = models.CharField(max_length=150, blank=True)
    actual_dosis_3 = models.IntegerField(null=True, blank=True)
    actual_ciclos_planeados_3 = models.IntegerField(null=True, blank=True)
    actual_ciclos_aplicados_3 = models.IntegerField(null=True, blank=True)
    actual_intervalo_3 = models.IntegerField(null=True, blank=True)
    actual_marca_4 = models.CharField(max_length=150, blank=True)
    actual_sal_4 = models.CharField(max_length=150, blank=True)
    actual_dosis_4 = models.IntegerField(null=True, blank=True)
    actual_ciclos_planeados_4 = models.IntegerField(null=True, blank=True)
    actual_ciclos_aplicados_4 = models.IntegerField(null=True, blank=True)
    actual_intervalo_4 = models.IntegerField(null=True, blank=True)
    actual_marca_5 = models.CharField(max_length=150, blank=True)
    actual_sal_5 = models.CharField(max_length=150, blank=True)
    actual_dosis_5 = models.IntegerField(null=True, blank=True)
    actual_ciclos_planeados_5 = models.IntegerField(null=True, blank=True)
    actual_ciclos_aplicados_5 = models.IntegerField(null=True, blank=True)
    actual_intervalo_5 = models.IntegerField(null=True, blank=True)
    actual_marca_6 = models.CharField(max_length=150, blank=True)
    actual_sal_6 = models.CharField(max_length=150, blank=True)
    actual_dosis_6 = models.IntegerField(null=True, blank=True)
    actual_ciclos_planeados_6 = models.IntegerField(null=True, blank=True)
    actual_ciclos_aplicados_6 = models.IntegerField(null=True, blank=True)
    actual_intervalo_6 = models.IntegerField(null=True, blank=True)
    actual_tipo_rituximab = models.CharField(max_length=45, blank=True)
    actual_efectos_adversos = models.CharField(max_length=180, blank=True)
    actual_fecha_inicio_1 = models.DateField(null=True, blank=True)
    actual_fecha_inicio_2 = models.DateField(null=True, blank=True)
    actual_fecha_inicio_3 = models.DateField(null=True, blank=True)
    actual_fecha_inicio_4 = models.DateField(null=True, blank=True)
    actual_fecha_inicio_5 = models.DateField(null=True, blank=True)
    actual_fecha_inicio_6 = models.DateField(null=True, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl4_hemato'

class Tbl5Hemato(models.Model):
    id_tbl5 = models.IntegerField(primary_key=True)
    id_tbl1 = models.ForeignKey(Tbl1Hemato, db_column='id_tbl1')
    previo1_tratamiento_linea = models.CharField(max_length=30, blank=True)
    previo1_tratamiento_tipo = models.CharField(max_length=45, blank=True)
    previo1_mabthera = models.CharField(max_length=30, blank=True)
    previo1_despues_de_cuantos_meses_recayo = models.IntegerField(null=True, blank=True)
    previo1_marca_1 = models.CharField(max_length=150, blank=True)
    previo1_sal_1 = models.CharField(max_length=150, blank=True)
    previo1_dosis_1 = models.IntegerField(null=True, blank=True)
    previo1_fecha_inicio_1 = models.DateField(null=True, blank=True)
    previo1_ciclos_aplicados_1 = models.IntegerField(null=True, blank=True)
    previo1_intervalo_1 = models.IntegerField(null=True, blank=True)
    previo1_marca_2 = models.CharField(max_length=150, blank=True)
    previo1_sal_2 = models.CharField(max_length=150, blank=True)
    previo1_dosis_2 = models.IntegerField(null=True, blank=True)
    previo1_fecha_inicio_2 = models.DateField(null=True, blank=True)
    previo1_ciclos_aplicados_2 = models.IntegerField(null=True, blank=True)
    previo1_intervalo_2 = models.IntegerField(null=True, blank=True)
    previo1_marca_3 = models.CharField(max_length=150, blank=True)
    previo1_sal_3 = models.CharField(max_length=150, blank=True)
    previo1_dosis_3 = models.IntegerField(null=True, blank=True)
    previo1_fecha_inicio_3 = models.DateField(null=True, blank=True)
    previo1_ciclos_aplicados_3 = models.IntegerField(null=True, blank=True)
    previo1_intervalo_3 = models.IntegerField(null=True, blank=True)
    previo1_marca_4 = models.CharField(max_length=150, blank=True)
    previo1_sal_4 = models.CharField(max_length=150, blank=True)
    previo1_dosis_4 = models.IntegerField(null=True, blank=True)
    previo1_fecha_inicio_4 = models.DateField(null=True, blank=True)
    previo1_ciclos_aplicados_4 = models.IntegerField(null=True, blank=True)
    previo1_intervalo_4 = models.IntegerField(null=True, blank=True)
    previo1_marca_5 = models.CharField(max_length=150, blank=True)
    previo1_sal_5 = models.CharField(max_length=150, blank=True)
    previo1_dosis_5 = models.IntegerField(null=True, blank=True)
    previo1_fecha_inicio_5 = models.DateField(null=True, blank=True)
    previo1_ciclos_aplicados_5 = models.IntegerField(null=True, blank=True)
    previo1_intervalo_5 = models.IntegerField(null=True, blank=True)
    previo1_marca_6 = models.CharField(max_length=150, blank=True)
    previo1_sal_6 = models.CharField(max_length=150, blank=True)
    previo1_dosis_6 = models.IntegerField(null=True, blank=True)
    previo1_fecha_inicio_6 = models.DateField(null=True, blank=True)
    previo1_ciclos_aplicados_6 = models.IntegerField(null=True, blank=True)
    previo1_intervalo_6 = models.IntegerField(null=True, blank=True)
    previo1_tipo_rituximab = models.CharField(max_length=45, blank=True)
    previo1_efectos_adversos = models.CharField(max_length=180, blank=True)
    previo1_utilizo_fec = models.CharField(max_length=6, blank=True)
    previo1_desarrollo_neutropenia = models.CharField(max_length=6, blank=True)
    previo1_ciclos_mantenimiento = models.IntegerField(null=True, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl5_hemato'

class Tbl6Hemato(models.Model):
    id_tbl6 = models.IntegerField(primary_key=True)
    id_tbl1 = models.ForeignKey(Tbl1Hemato, db_column='id_tbl1')
    previo2_tratamiento_linea = models.CharField(max_length=30, blank=True)
    previo2_mabthera = models.CharField(max_length=30, blank=True)
    previo2_tratamiento_tipo = models.CharField(max_length=45, blank=True)
    previo2_despues_de_cuantos_meses_recayo = models.IntegerField(null=True, blank=True)
    previo2_marca_1 = models.CharField(max_length=150, blank=True)
    previo2_sal_1 = models.CharField(max_length=150, blank=True)
    previo2_dosis_1 = models.IntegerField(null=True, blank=True)
    previo2_fecha_inicio_1 = models.DateField(null=True, blank=True)
    previo2_ciclos_aplicados_1 = models.IntegerField(null=True, blank=True)
    previo2_intervalo_1 = models.IntegerField(null=True, blank=True)
    previo2_marca_2 = models.CharField(max_length=150, blank=True)
    previo2_sal_2 = models.CharField(max_length=150, blank=True)
    previo2_dosis_2 = models.IntegerField(null=True, blank=True)
    previo2_fecha_inicio_2 = models.DateField(null=True, blank=True)
    previo2_ciclos_aplicados_2 = models.IntegerField(null=True, blank=True)
    previo2_intervalo_2 = models.IntegerField(null=True, blank=True)
    previo2_marca_3 = models.CharField(max_length=150, blank=True)
    previo2_sal_3 = models.CharField(max_length=150, blank=True)
    previo2_dosis_3 = models.IntegerField(null=True, blank=True)
    previo2_fecha_inicio_3 = models.DateField(null=True, blank=True)
    previo2_ciclos_aplicados_3 = models.IntegerField(null=True, blank=True)
    previo2_intervalo_3 = models.IntegerField(null=True, blank=True)
    previo2_marca_4 = models.CharField(max_length=150, blank=True)
    previo2_sal_4 = models.CharField(max_length=150, blank=True)
    previo2_dosis_4 = models.IntegerField(null=True, blank=True)
    previo2_fecha_inicio_4 = models.DateField(null=True, blank=True)
    previo2_ciclos_aplicados_4 = models.IntegerField(null=True, blank=True)
    previo2_intervalo_4 = models.IntegerField(null=True, blank=True)
    previo2_marca_5 = models.CharField(max_length=150, blank=True)
    previo2_sal_5 = models.CharField(max_length=150, blank=True)
    previo2_dosis_5 = models.IntegerField(null=True, blank=True)
    previo2_fecha_inicio_5 = models.DateField(null=True, blank=True)
    previo2_ciclos_aplicados_5 = models.IntegerField(null=True, blank=True)
    previo2_intervalo_5 = models.IntegerField(null=True, blank=True)
    previo2_marca_6 = models.CharField(max_length=150, blank=True)
    previo2_sal_6 = models.CharField(max_length=150, blank=True)
    previo2_dosis_6 = models.IntegerField(null=True, blank=True)
    previo2_fecha_inicio_6 = models.DateField(null=True, blank=True)
    previo2_ciclos_aplicados_6 = models.IntegerField(null=True, blank=True)
    previo2_intervalo_6 = models.IntegerField(null=True, blank=True)
    previo2_tipo_rituximab = models.CharField(max_length=45, blank=True)
    previo2_efectos_adversos = models.CharField(max_length=180, blank=True)
    previo2_utilizo_fec = models.CharField(max_length=6, blank=True)
    previo2_desarrollo_neutropenia = models.CharField(max_length=6, blank=True)
    previo2_ciclos_mantenimiento = models.IntegerField(null=True, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl6_hemato'

class Tbl7Hemato(models.Model):
    id_tbl7 = models.IntegerField(primary_key=True)
    id_tbl1 = models.ForeignKey(Tbl1Hemato, db_column='id_tbl1')
    previo3_tratamiento_linea = models.CharField(max_length=30, blank=True)
    previo3_mabthera = models.CharField(max_length=30, blank=True)
    previo3_tratamiento_tipo = models.CharField(max_length=45, blank=True)
    previo3_despues_de_cuantos_meses_recayo = models.IntegerField(null=True, blank=True)
    previo3_marca_1 = models.CharField(max_length=150, blank=True)
    previo3_sal_1 = models.CharField(max_length=150, blank=True)
    previo3_dosis_1 = models.IntegerField(null=True, blank=True)
    previo3_fecha_inicio_1 = models.DateField(null=True, blank=True)
    previo3_ciclos_aplicados_1 = models.IntegerField(null=True, blank=True)
    previo3_intervalo_1 = models.IntegerField(null=True, blank=True)
    previo3_marca_2 = models.CharField(max_length=150, blank=True)
    previo3_sal_2 = models.CharField(max_length=150, blank=True)
    previo3_dosis_2 = models.IntegerField(null=True, blank=True)
    previo3_fecha_inicio_2 = models.DateField(null=True, blank=True)
    previo3_ciclos_aplicados_2 = models.IntegerField(null=True, blank=True)
    previo3_intervalo_2 = models.IntegerField(null=True, blank=True)
    previo3_marca_3 = models.CharField(max_length=150, blank=True)
    previo3_sal_3 = models.CharField(max_length=150, blank=True)
    previo3_dosis_3 = models.IntegerField(null=True, blank=True)
    previo3_fecha_inicio_3 = models.DateField(null=True, blank=True)
    previo3_ciclos_aplicados_3 = models.IntegerField(null=True, blank=True)
    previo3_intervalo_3 = models.IntegerField(null=True, blank=True)
    previo3_marca_4 = models.CharField(max_length=150, blank=True)
    previo3_sal_4 = models.CharField(max_length=150, blank=True)
    previo3_dosis_4 = models.IntegerField(null=True, blank=True)
    previo3_fecha_inicio_4 = models.DateField(null=True, blank=True)
    previo3_ciclos_aplicados_4 = models.IntegerField(null=True, blank=True)
    previo3_intervalo_4 = models.IntegerField(null=True, blank=True)
    previo3_marca_5 = models.CharField(max_length=150, blank=True)
    previo3_sal_5 = models.CharField(max_length=150, blank=True)
    previo3_dosis_5 = models.IntegerField(null=True, blank=True)
    previo3_fecha_inicio_5 = models.DateField(null=True, blank=True)
    previo3_ciclos_aplicados_5 = models.IntegerField(null=True, blank=True)
    previo3_intervalo_5 = models.IntegerField(null=True, blank=True)
    previo3_marca_6 = models.CharField(max_length=150, blank=True)
    previo3_sal_6 = models.CharField(max_length=150, blank=True)
    previo3_dosis_6 = models.IntegerField(null=True, blank=True)
    previo3_fecha_inicio_6 = models.DateField(null=True, blank=True)
    previo3_ciclos_aplicados_6 = models.IntegerField(null=True, blank=True)
    previo3_intervalo_6 = models.IntegerField(null=True, blank=True)
    previo3_tipo_rituximab = models.CharField(max_length=45, blank=True)
    previo3_efectos_adversos = models.CharField(max_length=180, blank=True)
    previo3_utilizo_fec = models.CharField(max_length=6, blank=True)
    previo3_desarrollo_neutropenia = models.CharField(max_length=6, blank=True)
    previo3_ciclos_mantenimiento = models.IntegerField(null=True, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl7_hemato'

class Tbl8Hemato(models.Model):
    id_tbl8 = models.IntegerField(primary_key=True)
    id_tbl1 = models.ForeignKey(Tbl1Hemato, db_column='id_tbl1')
    previo4_tratamiento_linea = models.CharField(max_length=30, blank=True)
    previo4_mabthera = models.CharField(max_length=30, blank=True)
    previo4_tratamiento_tipo = models.CharField(max_length=45, blank=True)
    previo4_despues_de_cuantos_meses_recayo = models.IntegerField(null=True, blank=True)
    previo4_marca_1 = models.CharField(max_length=150, blank=True)
    previo4_sal_1 = models.CharField(max_length=150, blank=True)
    previo4_dosis_1 = models.IntegerField(null=True, blank=True)
    previo4_fecha_inicio_1 = models.DateField(null=True, blank=True)
    previo4_ciclos_aplicados_1 = models.IntegerField(null=True, blank=True)
    previo4_intervalo_1 = models.IntegerField(null=True, blank=True)
    previo4_marca_2 = models.CharField(max_length=150, blank=True)
    previo4_sal_2 = models.CharField(max_length=150, blank=True)
    previo4_dosis_2 = models.IntegerField(null=True, blank=True)
    previo4_fecha_inicio_2 = models.DateField(null=True, blank=True)
    previo4_ciclos_aplicados_2 = models.IntegerField(null=True, blank=True)
    previo4_intervalo_2 = models.IntegerField(null=True, blank=True)
    previo4_marca_3 = models.CharField(max_length=150, blank=True)
    previo4_sal_3 = models.CharField(max_length=150, blank=True)
    previo4_dosis_3 = models.IntegerField(null=True, blank=True)
    previo4_fecha_inicio_3 = models.DateField(null=True, blank=True)
    previo4_ciclos_aplicados_3 = models.IntegerField(null=True, blank=True)
    previo4_intervalo_3 = models.IntegerField(null=True, blank=True)
    previo4_marca_4 = models.CharField(max_length=150, blank=True)
    previo4_sal_4 = models.CharField(max_length=150, blank=True)
    previo4_dosis_4 = models.IntegerField(null=True, blank=True)
    previo4_fecha_inicio_4 = models.DateField(null=True, blank=True)
    previo4_ciclos_aplicados_4 = models.IntegerField(null=True, blank=True)
    previo4_intervalo_4 = models.IntegerField(null=True, blank=True)
    previo4_marca_5 = models.CharField(max_length=150, blank=True)
    previo4_sal_5 = models.CharField(max_length=150, blank=True)
    previo4_dosis_5 = models.IntegerField(null=True, blank=True)
    previo4_fecha_inicio_5 = models.DateField(null=True, blank=True)
    previo4_ciclos_aplicados_5 = models.IntegerField(null=True, blank=True)
    previo4_intervalo_5 = models.IntegerField(null=True, blank=True)
    previo4_marca_6 = models.CharField(max_length=150, blank=True)
    previo4_sal_6 = models.CharField(max_length=150, blank=True)
    previo4_dosis_6 = models.IntegerField(null=True, blank=True)
    previo4_fecha_inicio_6 = models.DateField(null=True, blank=True)
    previo4_ciclos_aplicados_6 = models.IntegerField(null=True, blank=True)
    previo4_intervalo_6 = models.IntegerField(null=True, blank=True)
    previo4_tipo_rituximab = models.CharField(max_length=45, blank=True)
    previo4_efectos_adversos = models.CharField(max_length=180, blank=True)
    previo4_utilizo_fec = models.CharField(max_length=6, blank=True)
    previo4_desarrollo_neutropenia = models.CharField(max_length=6, blank=True)
    previo4_ciclos_mantenimiento = models.IntegerField(null=True, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl8_hemato'

class Tbl9Hemato(models.Model):
    id_tbl9 = models.IntegerField(primary_key=True)
    id_tbl1 = models.ForeignKey(Tbl1Hemato, db_column='id_tbl1')
    previo5_tratamiento_linea = models.CharField(max_length=30, blank=True)
    previo5_mabthera = models.CharField(max_length=30, blank=True)
    previo5_tratamiento_tipo = models.CharField(max_length=45, blank=True)
    previo5_despues_de_cuantos_meses_recayo = models.IntegerField(null=True, blank=True)
    previo5_marca_1 = models.CharField(max_length=150, blank=True)
    previo5_sal_1 = models.CharField(max_length=150, blank=True)
    previo5_dosis_1 = models.IntegerField(null=True, blank=True)
    previo5_fecha_inicio_1 = models.DateField(null=True, blank=True)
    previo5_ciclos_aplicados_1 = models.IntegerField(null=True, blank=True)
    previo5_intervalo_1 = models.IntegerField(null=True, blank=True)
    previo5_marca_2 = models.CharField(max_length=150, blank=True)
    previo5_sal_2 = models.CharField(max_length=150, blank=True)
    previo5_dosis_2 = models.IntegerField(null=True, blank=True)
    previo5_fecha_inicio_2 = models.DateField(null=True, blank=True)
    previo5_ciclos_aplicados_2 = models.IntegerField(null=True, blank=True)
    previo5_intervalo_2 = models.IntegerField(null=True, blank=True)
    previo5_marca_3 = models.CharField(max_length=150, blank=True)
    previo5_sal_3 = models.CharField(max_length=150, blank=True)
    previo5_dosis_3 = models.IntegerField(null=True, blank=True)
    previo5_fecha_inicio_3 = models.DateField(null=True, blank=True)
    previo5_ciclos_aplicados_3 = models.IntegerField(null=True, blank=True)
    previo5_intervalo_3 = models.IntegerField(null=True, blank=True)
    previo5_marca_4 = models.CharField(max_length=150, blank=True)
    previo5_sal_4 = models.CharField(max_length=150, blank=True)
    previo5_dosis_4 = models.IntegerField(null=True, blank=True)
    previo5_fecha_inicio_4 = models.DateField(null=True, blank=True)
    previo5_ciclos_aplicados_4 = models.IntegerField(null=True, blank=True)
    previo5_intervalo_4 = models.IntegerField(null=True, blank=True)
    previo5_marca_5 = models.CharField(max_length=150, blank=True)
    previo5_sal_5 = models.CharField(max_length=150, blank=True)
    previo5_dosis_5 = models.IntegerField(null=True, blank=True)
    previo5_fecha_inicio_5 = models.DateField(null=True, blank=True)
    previo5_ciclos_aplicados_5 = models.IntegerField(null=True, blank=True)
    previo5_intervalo_5 = models.IntegerField(null=True, blank=True)
    previo5_marca_6 = models.CharField(max_length=150, blank=True)
    previo5_sal_6 = models.CharField(max_length=150, blank=True)
    previo5_dosis_6 = models.IntegerField(null=True, blank=True)
    previo5_fecha_inicio_6 = models.DateField(null=True, blank=True)
    previo5_ciclos_aplicados_6 = models.IntegerField(null=True, blank=True)
    previo5_intervalo_6 = models.IntegerField(null=True, blank=True)
    previo5_tipo_rituximab = models.CharField(max_length=45, blank=True)
    previo5_efectos_adversos = models.CharField(max_length=180, blank=True)
    previo5_utilizo_fec = models.CharField(max_length=6, blank=True)
    previo5_desarrollo_neutropenia = models.CharField(max_length=6, blank=True)
    previo5_ciclos_mantenimiento = models.IntegerField(null=True, blank=True)
    hora = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = u'tbl9_hemato'

